services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - ./.env
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    depends_on:
      - mongodb

  backend:
    container_name: "backend"
    restart: always
    build:
      context: ./apps/backend/
      dockerfile: dockerfile
    depends_on:
      - mongodb
    env_file:
      - ./.env

  backend-gui:
    container_name: "backend-gui"
    build:
      context: .
      dockerfile: ./apps/backend-gui/dockerfile
    depends_on:
      - backend
    ports:
      - 8080:8080

  frontend:
    container_name: "frontend"
    build:
      context: .
      dockerfile: ./apps/frontend/dockerfile
    depends_on:
      - backend
    ports:
      - 80:80

volumes:
  mongodb:
